// ---------------------------------------------------------------------------
// seed.js
// Realistic but entirely fictional starter data so the tool looks like a real
// bank's model landscape the first time it is opened. The five factor scores
// (materiality, complexity, reliance, regulatory, uncertainty) are INPUTS that
// were assessed for each model; the tool computes the tier from them.
// ---------------------------------------------------------------------------

export function buildSeedData() {
  const models = [
    {
      id: 'MDL-001',
      name: 'Retail Mortgage PD',
      purpose: 'Estimates the probability of default for the residential mortgage portfolio; feeds IRB capital and IFRS 9 staging.',
      owner: 'James Whitfield',
      developer: 'Retail Credit Analytics',
      validator: 'Elena Fischer',
      businessUnit: 'Retail Banking',
      modelType: 'PD (Probability of Default)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2019-04-01',
      lastValidated: '2025-05-20',
      limitations: 'Rank-ordering weakens in the high-LTV segment; calibration sensitive to house-price assumptions.',
      materiality: 3, complexity: 2, reliance: 3, regulatory: 3, uncertainty: 2,
    },
    {
      id: 'MDL-002',
      name: 'Credit Card PD',
      purpose: 'Behavioural probability-of-default model for the revolving credit card book; used for capital and impairment.',
      owner: 'James Whitfield',
      developer: 'Retail Credit Analytics',
      validator: 'Raj Patel',
      businessUnit: 'Cards & Unsecured',
      modelType: 'PD (Probability of Default)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2020-02-15',
      lastValidated: '2025-09-10',
      limitations: 'Sensitive to rapid shifts in revolver behaviour; bureau attributes have minor data-quality gaps.',
      materiality: 3, complexity: 2, reliance: 2, regulatory: 3, uncertainty: 2,
    },
    {
      id: 'MDL-003',
      name: 'SME / Small Business PD',
      purpose: 'Probability of default for small-business lending under the standardised approach.',
      owner: 'Sofia Almeida',
      developer: 'Wholesale Risk Analytics',
      validator: 'Raj Patel',
      businessUnit: 'Business & Commercial Banking',
      modelType: 'PD (Probability of Default)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2021-06-01',
      lastValidated: '2024-09-20',
      limitations: 'Sparse default data in some sectors; heavy reliance on financial-statement inputs of variable quality.',
      materiality: 2, complexity: 2, reliance: 2, regulatory: 2, uncertainty: 3,
    },
    {
      id: 'MDL-004',
      name: 'Retail Mortgage LGD',
      purpose: 'Loss-given-default for residential mortgages, including downturn calibration; feeds capital and ECL.',
      owner: 'Sofia Almeida',
      developer: 'Retail Credit Analytics',
      validator: 'Elena Fischer',
      businessUnit: 'Retail Banking',
      modelType: 'LGD (Loss Given Default)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2019-04-01',
      lastValidated: '2025-06-15',
      limitations: 'Downturn LGD floor relies partly on pre-2012 data; limited recent recovery observations.',
      materiality: 3, complexity: 2, reliance: 3, regulatory: 3, uncertainty: 3,
    },
    {
      id: 'MDL-005',
      name: 'Retail Mortgage EAD / CCF',
      purpose: 'Exposure-at-default and credit-conversion-factor model for mortgage commitments and offset facilities.',
      owner: 'James Whitfield',
      developer: 'Retail Credit Analytics',
      validator: 'Elena Fischer',
      businessUnit: 'Retail Banking',
      modelType: 'EAD (Exposure at Default)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2019-04-01',
      lastValidated: '2025-02-10',
      limitations: 'Limited variation in drawdown behaviour; CCF assumptions conservative by design.',
      materiality: 2, complexity: 2, reliance: 2, regulatory: 3, uncertainty: 2,
    },
    {
      id: 'MDL-006',
      name: 'IFRS 9 Retail ECL',
      purpose: 'Expected-credit-loss engine for the retail book; combines PD/LGD/EAD with forward-looking macro scenarios. Feeds financial reporting.',
      owner: 'Priya Nair',
      developer: 'Impairment Analytics',
      validator: 'Claire Dubois',
      businessUnit: 'Finance',
      modelType: 'IFRS 9 / Impairment (ECL)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: ['MDL-001', 'MDL-004', 'MDL-005'],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2018-01-01',
      lastValidated: '2024-11-30',
      limitations: 'Macro scenario weights need regular refresh; staging transfer logic sensitive to thresholds.',
      materiality: 3, complexity: 3, reliance: 2, regulatory: 3, uncertainty: 3,
    },
    {
      id: 'MDL-007',
      name: 'Corporate / Wholesale PD',
      purpose: 'Rating-based probability of default for large corporate and institutional counterparties.',
      owner: 'Sofia Almeida',
      developer: 'Wholesale Risk Analytics',
      validator: 'Raj Patel',
      businessUnit: 'Corporate & Institutional Banking',
      modelType: 'PD (Probability of Default)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2020-09-01',
      lastValidated: '2025-12-01',
      limitations: 'Expert-judgement overrides exceed policy threshold; low-default portfolio limits back-testing power.',
      materiality: 2, complexity: 2, reliance: 3, regulatory: 3, uncertainty: 3,
    },
    {
      id: 'MDL-008',
      name: 'Wholesale LGD',
      purpose: 'Loss-given-default for corporate and institutional exposures; feeds IRB capital.',
      owner: 'Tom Castellano',
      developer: 'Wholesale Risk Analytics',
      validator: 'Raj Patel',
      businessUnit: 'Corporate & Institutional Banking',
      modelType: 'LGD (Loss Given Default)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2020-09-01',
      lastValidated: '2023-06-01',
      limitations: 'Low-default portfolio; limited data to evidence calibration of recovery rates.',
      materiality: 2, complexity: 2, reliance: 2, regulatory: 3, uncertainty: 2,
    },
    {
      id: 'MDL-009',
      name: 'Card Fraud Detection',
      purpose: 'Real-time machine-learning model that scores card transactions for fraud and triggers step-up/decline.',
      owner: 'Daniel Okafor',
      developer: 'Data Science Lab',
      validator: 'Claire Dubois',
      businessUnit: 'Cards & Unsecured',
      modelType: 'Fraud (ML classifier)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: false,
      status: 'in_use',
      goLiveDate: '2022-03-10',
      lastValidated: '2025-03-01',
      limitations: 'Subject to model drift as fraud patterns evolve; limited explainability of individual scores.',
      materiality: 2, complexity: 3, reliance: 2, regulatory: 1, uncertainty: 2,
    },
    {
      id: 'MDL-010',
      name: 'AML Transaction Monitoring',
      purpose: 'Rule- and scenario-based monitoring of transactions for money-laundering typologies; generates regulatory SARs.',
      owner: 'Aisha Rahman',
      developer: 'Vantor Technologies',
      validator: 'Claire Dubois',
      businessUnit: 'Financial Crime',
      modelType: 'AML / Transaction Monitoring',
      buildType: 'vendor',
      vendorName: 'Nexus FinCrime Suite (Vantor)',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2021-11-01',
      lastValidated: '2024-07-15',
      limitations: 'Threshold tuning not fully transparent (vendor logic); risk of under-alerting on novel typologies.',
      materiality: 2, complexity: 2, reliance: 1, regulatory: 3, uncertainty: 2,
    },
    {
      id: 'MDL-011',
      name: 'Mortgage Pricing',
      purpose: 'Risk-based pricing engine for new mortgage business; uses PD and LGD outputs to set rates.',
      owner: 'Hannah Berg',
      developer: 'Retail Pricing',
      validator: 'Elena Fischer',
      businessUnit: 'Retail Banking',
      modelType: 'Pricing',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: ['MDL-001', 'MDL-004'],
      regulatoryUse: false,
      status: 'in_use',
      goLiveDate: '2021-01-15',
      lastValidated: '2024-04-01',
      limitations: 'Competitor-response assumptions are static; elasticity estimates based on a short history.',
      materiality: 2, complexity: 2, reliance: 2, regulatory: 1, uncertainty: 2,
    },
    {
      id: 'MDL-012',
      name: 'Legacy Retail Application Scorecard',
      purpose: 'Original application scorecard for unsecured lending. Retired and replaced by the current PD suite.',
      owner: 'James Whitfield',
      developer: 'Retail Credit Analytics',
      validator: 'Raj Patel',
      businessUnit: 'Cards & Unsecured',
      modelType: 'Application Scorecard',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: false,
      status: 'retired',
      goLiveDate: '2014-05-01',
      lastValidated: '2022-05-01',
      limitations: 'Superseded; retained for reference only. Decommissioned from all live decisioning.',
      materiality: 1, complexity: 1, reliance: 1, regulatory: 1, uncertainty: 2,
    },
    {
      id: 'MDL-013',
      name: 'Economic Capital (ICAAP)',
      purpose: 'Aggregates risk across the group to estimate economic capital; central input to the ICAAP.',
      owner: 'Marcus Lindqvist',
      developer: 'Capital Modelling',
      validator: 'Claire Dubois',
      businessUnit: 'Group Risk',
      modelType: 'Economic Capital',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: ['MDL-001', 'MDL-002', 'MDL-004', 'MDL-007', 'MDL-008'],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2018-06-01',
      lastValidated: '2025-08-05',
      limitations: 'Correlation assumptions hard to validate empirically; key-person dependency in the codebase.',
      materiality: 3, complexity: 3, reliance: 3, regulatory: 3, uncertainty: 3,
    },
    {
      id: 'MDL-014',
      name: 'Group Stress Testing',
      purpose: 'Projects losses, capital and P&L under regulatory and internal stress scenarios.',
      owner: 'Marcus Lindqvist',
      developer: 'Capital Modelling',
      validator: 'Claire Dubois',
      businessUnit: 'Group Risk',
      modelType: 'Stress Testing',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: ['MDL-006', 'MDL-013', 'MDL-001', 'MDL-007'],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2019-01-01',
      lastValidated: '2026-03-15',
      limitations: 'Manual spreadsheet steps in scenario expansion create operational risk; long run-times.',
      materiality: 3, complexity: 3, reliance: 2, regulatory: 3, uncertainty: 3,
    },
    {
      id: 'MDL-015',
      name: 'Counterparty Credit Risk / CVA',
      purpose: 'Computes counterparty exposure and credit valuation adjustment for derivatives.',
      owner: 'Tom Castellano',
      developer: 'Treasury Quant',
      validator: 'Raj Patel',
      businessUnit: 'Markets / Treasury',
      modelType: 'Counterparty Credit Risk (CVA)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2020-04-01',
      lastValidated: '2024-10-10',
      limitations: 'Reliant on market-data quality; reconciliation between front-office and risk CVA not fully documented.',
      materiality: 2, complexity: 3, reliance: 1, regulatory: 3, uncertainty: 2,
    },
    {
      id: 'MDL-016',
      name: 'IRRBB / Banking Book Rate Risk',
      purpose: 'Measures interest-rate risk in the banking book, including EVE and NII sensitivities.',
      owner: 'Hannah Berg',
      developer: 'Treasury Quant',
      validator: 'Raj Patel',
      businessUnit: 'Markets / Treasury',
      modelType: 'IRRBB / ALM',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2020-07-01',
      lastValidated: '2025-01-20',
      limitations: 'Behavioural assumptions (prepayment, non-maturing deposits) are judgement-heavy.',
      materiality: 2, complexity: 2, reliance: 2, regulatory: 2, uncertainty: 2,
    },
    {
      id: 'MDL-017',
      name: 'Liquidity Coverage (LCR)',
      purpose: 'Calculates the liquidity coverage ratio and projects cash-flow stress for regulatory liquidity reporting.',
      owner: 'Hannah Berg',
      developer: 'Treasury Quant',
      validator: 'Claire Dubois',
      businessUnit: 'Markets / Treasury',
      modelType: 'Liquidity / LCR',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2019-09-01',
      lastValidated: '2024-12-05',
      limitations: 'Outflow assumptions are conservative; limited stress data for deposit run-off behaviour.',
      materiality: 2, complexity: 2, reliance: 1, regulatory: 3, uncertainty: 2,
    },
    {
      id: 'MDL-018',
      name: 'Customer Churn Propensity',
      purpose: 'Machine-learning model predicting attrition to prioritise retention marketing.',
      owner: 'Daniel Okafor',
      developer: 'Data Science Lab',
      validator: 'Raj Patel',
      businessUnit: 'Retail Banking',
      modelType: 'Marketing / Propensity (ML)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: false,
      status: 'in_use',
      goLiveDate: '2022-08-01',
      lastValidated: '2024-02-15',
      limitations: 'Feature importance shifts over time; uplift assumptions need periodic revalidation.',
      materiality: 1, complexity: 3, reliance: 1, regulatory: 1, uncertainty: 2,
    },
    {
      id: 'MDL-019',
      name: 'Retail PD Challenger (ML)',
      purpose: 'Machine-learning challenger to the retail mortgage PD model, in development to benchmark the incumbent.',
      owner: 'James Whitfield',
      developer: 'Data Science Lab',
      validator: 'Elena Fischer',
      businessUnit: 'Retail Banking',
      modelType: 'PD (ML challenger)',
      buildType: 'in-house',
      vendorName: '',
      dependsOn: [],
      regulatoryUse: false,
      status: 'development',
      goLiveDate: '',
      lastValidated: '',
      limitations: 'Under construction; explainability and stability still being assessed before any production use.',
      materiality: 2, complexity: 3, reliance: 1, regulatory: 2, uncertainty: 3,
    },
    {
      id: 'MDL-020',
      name: 'Climate Risk Scenario',
      purpose: 'Vendor scenario model translating climate pathways into credit and market risk impacts for regulatory climate stress testing.',
      owner: 'Marcus Lindqvist',
      developer: 'GreenScope Analytics',
      validator: 'Claire Dubois',
      businessUnit: 'Group Risk',
      modelType: 'Climate Risk Scenario',
      buildType: 'vendor',
      vendorName: 'ClimaRisk Analytics (GreenScope)',
      dependsOn: [],
      regulatoryUse: true,
      status: 'in_use',
      goLiveDate: '2023-05-30',
      lastValidated: '2025-05-30',
      limitations: 'Emerging methodology with deep uncertainty; vendor scenario engine is partly a black box.',
      materiality: 2, complexity: 3, reliance: 1, regulatory: 2, uncertainty: 3,
    },
  ];

  const findings = [
    {
      id: 'FND-001', modelId: 'MDL-006', source: 'Validation', severity: 'High',
      description: 'Macroeconomic scenario weights not refreshed for the latest forecast vintage; ECL may be understated.',
      owner: 'Priya Nair', dateRaised: '2025-12-10', targetDate: '2026-04-30', status: 'In Progress',
    },
    {
      id: 'FND-002', modelId: 'MDL-001', source: 'Validation', severity: 'High',
      description: 'Rank-ordering deterioration observed in 2025 back-testing for the high-LTV segment.',
      owner: 'James Whitfield', dateRaised: '2026-01-15', targetDate: '2026-07-31', status: 'Open',
    },
    {
      id: 'FND-003', modelId: 'MDL-001', source: 'Ongoing Monitoring', severity: 'Medium',
      description: 'Population Stability Index breach (PSI > 0.25) on new-business scores; investigate population shift.',
      owner: 'James Whitfield', dateRaised: '2026-05-02', targetDate: '2026-08-15', status: 'Open',
    },
    {
      id: 'FND-004', modelId: 'MDL-013', source: 'Internal Audit', severity: 'Critical',
      description: 'Inadequate documentation of correlation assumptions; single key-person dependency in the production code.',
      owner: 'Marcus Lindqvist', dateRaised: '2025-09-30', targetDate: '2026-03-31', status: 'In Progress',
    },
    {
      id: 'FND-005', modelId: 'MDL-010', source: 'Regulator', severity: 'High',
      description: 'Threshold tuning not independently validated; potential under-alerting on layering typologies.',
      owner: 'Aisha Rahman', dateRaised: '2026-02-20', targetDate: '2026-06-15', status: 'In Progress',
    },
    {
      id: 'FND-006', modelId: 'MDL-009', source: 'Ongoing Monitoring', severity: 'Medium',
      description: 'Model drift: precision down ~6% quarter-on-quarter; retraining cadence under review.',
      owner: 'Daniel Okafor', dateRaised: '2026-04-10', targetDate: '2026-09-30', status: 'Open',
    },
    {
      id: 'FND-007', modelId: 'MDL-004', source: 'Validation', severity: 'Medium',
      description: 'Downturn LGD floor calibration relies on pre-2012 data; refresh with recent recovery observations.',
      owner: 'Sofia Almeida', dateRaised: '2025-07-01', targetDate: '2026-02-28', status: 'Fixed',
    },
    {
      id: 'FND-008', modelId: 'MDL-014', source: 'Internal Audit', severity: 'High',
      description: 'Manual spreadsheet steps in scenario expansion create operational risk; automate and add controls.',
      owner: 'Hannah Berg', dateRaised: '2026-03-20', targetDate: '2026-09-15', status: 'Open',
    },
    {
      id: 'FND-009', modelId: 'MDL-008', source: 'Validation', severity: 'Medium',
      description: 'Low-default portfolio; limited data to evidence recovery-rate calibration. Supplement with external benchmarks.',
      owner: 'Tom Castellano', dateRaised: '2025-06-15', targetDate: '2025-12-31', status: 'In Progress',
    },
    {
      id: 'FND-010', modelId: 'MDL-020', source: 'Validation', severity: 'Low',
      description: 'Vendor scenario methodology not fully transparent; document reliance on black-box outputs and obtain assurance.',
      owner: 'Hannah Berg', dateRaised: '2026-01-30', targetDate: '2026-12-31', status: 'Open',
    },
    {
      id: 'FND-011', modelId: 'MDL-002', source: 'Ongoing Monitoring', severity: 'Low',
      description: 'Minor data-quality gaps in bureau attributes (<2% missing); monitor and remediate at source.',
      owner: 'James Whitfield', dateRaised: '2026-05-20', targetDate: '2026-10-31', status: 'Open',
    },
    {
      id: 'FND-012', modelId: 'MDL-006', source: 'Regulator', severity: 'Medium',
      description: 'Disclosure granularity for staging transfers to be enhanced following regulator feedback.',
      owner: 'Priya Nair', dateRaised: '2025-11-05', targetDate: '2026-07-30', status: 'In Progress',
    },
    {
      id: 'FND-013', modelId: 'MDL-007', source: 'Validation', severity: 'High',
      description: 'Expert-judgement override rates exceed policy threshold; strengthen governance and rationale capture.',
      owner: 'Sofia Almeida', dateRaised: '2026-02-01', targetDate: '2026-05-31', status: 'Open',
    },
    {
      id: 'FND-014', modelId: 'MDL-015', source: 'Internal Audit', severity: 'Medium',
      description: 'Reconciliation between front-office and risk CVA not formally documented; create a controlled process.',
      owner: 'Tom Castellano', dateRaised: '2025-10-12', targetDate: '2026-04-15', status: 'Fixed',
    },
    {
      id: 'FND-015', modelId: 'MDL-018', source: 'Ongoing Monitoring', severity: 'Low',
      description: 'Feature importance has shifted; revalidate marketing uplift assumptions at next refresh.',
      owner: 'Daniel Okafor', dateRaised: '2026-04-25', targetDate: '2026-11-30', status: 'Open',
    },
  ];

  const settings = {
    validationIntervalsMonths: { 1: 12, 2: 24, 3: 36 },
    dueSoonWindowDays: 90,
  };

  return { models, findings, settings, meta: { seededAt: new Date().toISOString(), schemaVersion: 1 } };
}
